#!/bin/bash

echo "🧪 测试超强协议阻止功能..."

echo ""
echo "🔥 重点测试：阻止网站JS检测弹窗"
echo "========================================="
echo ""
echo "✅ 应用已启动并包含以下新功能："
echo "1. 🎭 协议伪装：让网站认为协议已支持"
echo "2. 🚨 弹窗拦截：直接阻止confirm/alert协议弹窗"
echo "3. 🛡️ 检测阻止：伪装navigator.isProtocolHandlerRegistered"
echo "4. 🔄 方法重写：重写所有协议处理方法"
echo ""
echo "🧪 现在请测试以下场景："
echo ""
echo "1. 在应用中访问测试页面: http://localhost:8080/test-protocol-page.html"
echo "2. 点击危险协议链接，观察是否有弹窗"
echo "3. 访问包含字节跳动API的页面"
echo "4. 查看控制台输出，确认拦截日志"
echo ""
echo "📍 测试重点："
echo "• ❌ 不应出现：'未设定用来打开URL bytedance://...'弹窗"
echo "• ❌ 不应出现：应用重复启动"
echo "• ✅ 应该看到：控制台显示 '🎭 伪装协议注册成功' 或 '🚨 阻止协议相关确认框'"
echo "• ✅ 应该正常：其他网页功能不受影响"
echo ""
echo "🚀 开始测试吧！"
